# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eb2141569914d88a468c8f8ae400b13d7d453a9aa1dd3f615a1290dd556c4baa347c4edbb9413c090dcfdcfe3eafdbc6694d2e880707aff3c08d3f0b2235b3e

test:
  secret_key_base: bc1d75840d5cd4ee5d0a4b69710afc72dfa010404354862c61d2cfe5ceb095253e7647879491892c42cf3e6887af5923d33f43f6ea7b09801a9dab647e1366d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
